[tool.poetry]
name = "innoframework"
version = "0.1.1"
description = ""
authors = ["Kazybek Askarbek <k.askarbek@innopolis.university>"]

[tool.poetry.dependencies]
python = "^3.8"
sklearn = "^0.0"
streamlit = "^1.5.1"
hydra-core = "^1.1.1"
torch = "^1.10.2"
segmentation-models-pytorch = "^0.2.1"
pytorch-lightning = "^1.5.10"
albumentations = "^1.1.0"
h5py = "^3.6.0"
setuptools = "59.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
