[tool.poetry]
name = "opennews"
version = "0.0.2"
description = "An open source scraper to get current news."
authors = ["Zeb Taylor <zceboys@gmail.com>"]
license = "LGPL-3.0"
readme = "README.md"
homepage="https://github.com/foxnerdsaysmoo/opennews"

[tool.poetry.dependencies]
python = ">=3.8"
requests = "*"
aiohttp = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
