[tool.poetry]
name = "asyncio_tcp_message_228"
version = "0.1.0"
description = ""
authors = ["eale <novode25@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
poetry = "^1.1.13"
install = "^1.3.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
