[tool.poetry]
name = "huichao-poetry-demo"
version = "0.1.1"
description = ""
authors = ["cheng-huichao <cheng.huichao@yahoo.com>"]

[tool.poetry.dependencies]
python = "^3.6"
urllib3 = "^1.26.8"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
