[build-system]
requires = ["setuptools", "wheel", "setuptools_scm", "dask-image", "av"]
build-backend = "setuptools.build_meta"


[tool.setuptools_scm]
write_to = "src/napari_video_cvdask/_version.py"
local_scheme = "no-local-version"