[tool.poetry]
name = "hasbulla_boom"
version = "3.2.2"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pytest-cov = "^3.0.0"
asyncio = "^3.4.3"
pytest = "^7.0.1"
pytest-asyncio = "^0.18.1"
aiomisc = "^15.6.8"

[tool.poetry.dev-dependencies]
black = "^22.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
