[tool.poetry]
name = "bandwidth_cli"
version = "0.1.0"
description = "CLI for Bandwidth API calls"
authors = ["Malaney J Hill <mhill@phone.com>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.0.4"
python-dotenv = "^0.19.2"
requests = "^2.27.1"
xmltodict = "^0.12.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
bandwidth-cli = 'bandwidth_cli.main:cli'
