[tool.poetry]
name = "opennews"
version = "0.1.1"
description = "An open source scraper to get current news."
authors = ["Zeb Taylor <zceboys@gmail.com>"]
license = "LGPL-3.0"
readme = "README.md"
homepage="https://github.com/foxnerdsaysmoo/opennews"

[tool.poetry.dependencies]
python = ">=3.8"
feedparser = "*"
grequests = "*"
aiohttp = "*"
pydantic = "*"
urllib3 = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
