[tool.poetry]
name = "jayspytools"
version = "0.1.1"
description = ""
authors = ["jaygovind-sahu <jaygovind.sahu@yahoo.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pyspark = "^3.2.1"

[tool.poetry.dev-dependencies]
prospector = "^1.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
