[tool.poetry]
name = "bloc_client"
version = "0.1.4"
description = "python client sdk for bloc"
authors = ["pillipanda <pillipanda@126.com>"]

[tool.poetry.dependencies]
python = "^3.6"
httpx = "^0.21.1"
pika = "^1.2.0"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
