[tool.poetry]
name = "metabase-data-api"
version = "0.1.1"
description = "A package for querying metabase data via api."

license = "MIT"

authors = [
    "Adrian Brudaru <adrian@scalevector.ai>",
    "Marcin Rudolf  <marcin@scalevector.ai>",
    "MÃ¤tthaus Krzykowski <matthaus@scalevector.ai>"
]

readme = "README.md"

repository = "https://github.com/scale-vector/metabase_data_api"
homepage = "https://github.com/scale-vector/metabase_data_api"

keywords = ["metabase"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.23.0"


[tool.poetry.dev-dependencies]
mypy = "^0.931"
types-requests = "^2.27.11"
