[tool.poetry]
name = "Redditsfinder"
version = "2.0.5"
description = "Archive a reddit user's post history. Formatted overview of a profile, JSON containing every post, and picture downloads."
authors = ["fitzy1293 <berkshiremind@gmail.com>"]
# New attributes
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Fitzy1293/redditsfinder"
repository = "https://github.com/Fitzy1293/redditsfinder"
keywords = ["reddit", "webscraping", "reddit-crawler", "pushshift"]

include = [
    "LICENSE",
]

[tool.poetry.dependencies]
# Updated Python version
python = "^3.7"
rich = "<8.0.0,>=11.0.0"
requests = "^2.27.1"

[tool.poetry.scripts]
redditsfinder = 'redditsfinder:main'

[build-system]
requires = ["poetry>=2.0.2"]
build-backend = "poetry.masonry.api"
